### ISSUE TITLE
Add multi-type variant for NwAreaOfEffect ->GetObjectsInShape

### ISSUE THREAD

**Issue by Mefi100** [nwn-dotnet/Anvil#207]
Hi, I encountered the following runtime exception. Is this because `GetObjectsInEffectArea<NwGameObject>()` is not supported? 
Would it be possible to add support multi-type variant for NwAreaOfEffect ->GetObjectsInShape? That would be very useful, as I would like Acid Fog do deal damage to creatures, doors and placeables. 

```
nwn_1    | Unhandled exception. System.InvalidOperationException: Type "NWN.API.NwGameObject" does not have a mapped native object!
nwn_1    |    at NWN.API.NwObject.GetNativeObjectInfo(Type type) in /home/runner/work/NWN.Managed/NWN.Managed/src/main/NWN/API/Object/NwObject.Create.cs:line 162
nwn_1    |    at NWN.API.NwObject.GetObjectType[T]() in /home/runner/work/NWN.Managed/NWN.Managed/src/main/NWN/API/Object/NwObject.Create.cs:line 144
nwn_1    |    at NWN.API.NwAreaOfEffect.GetObjectsInEffectArea[T]()+MoveNext() in /home/runner/work/NWN.Managed/NWN.Managed/src/main/NWN/API/Object/NwAreaOfEffect.cs:line 76
nwn_1    |    at KK2.Game.Feats.AcidFog.OnHeartbeat(CallInfo callInfo)
nwn_1    |    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
nwn_1    |    at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
nwn_1    |    at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

```cs
        [ScriptHandler("acidfog_hb")]
        private async void OnHeartbeat(CallInfo callInfo)
        {
            AreaOfEffectEvents.OnHeartbeat onHeartbeat = new AreaOfEffectEvents.OnHeartbeat();
            NwAreaOfEffect acidFog = onHeartbeat.Effect;

            int damageAmount = 0;
            Effect vis = Effect.VisualEffect(VfxType.ImpAcidS);

            if (acidFog.Creator is null || !acidFog.Creator.IsValid)
            {
                acidFog.Destroy();
                return;
            }

            if (acidFog.Creator is NwCreature caster)
            {
                damageAmount += caster.GetSkillRank(Kk2Skill.LoreChemistry) / 2;
            }

            IEnumerable<NwGameObject> objectsInsideFog = acidFog.GetObjectsInEffectArea<NwGameObject>();

            foreach (var target in objectsInsideFog)
            {
                if (target is (NwCreature or NwPlaceable or NwDoor) && !target.PlotFlag)
                {
                    float delay = RandGen.NextFloat(0.4f, 1.2f);
                    damageAmount += RandGen.Roll(6, 2);

                    //Set Damage Effect with the modified damage
                    Effect damage = Effect.Damage(damageAmount, DamageType.Acid);
                    //Apply damage and visuals
                    await NwTask.Delay(TimeSpan.FromSeconds(delay));
                    target.ApplyEffect(EffectDuration.Instant, vis);
                    target.ApplyEffect(EffectDuration.Instant, damage);
                }
            }
        }
```

**Comment by Jorteck** [comment]
You want to use the non-generic overload: https://nwn-dotnet.github.io/Anvil/classNWN_1_1API_1_1NwAreaOfEffect.html#ad42e343cf28ffdd27cae99660e7e1fd5
