### ISSUE TITLE
Possible NullReferenceException

### ISSUE THREAD

**Issue by Mefi100** [nwn-dotnet/Anvil#254]
I have observed that iterating over `NwModule.Instance.Players` sometimes is causing NullReferenceException. 

This is an edge case and happens when player is in the character selection menu. So technically, the player is already in, however has no character instance yet. 

```
nwn_1    | E [2021/05/06 11:39:54.866] [Anvil.Internal.CoreInteropHandler] System.NullReferenceException: Object reference not set to an instance of an object.
nwn_1    |    at NWN.API.NwCreature..ctor(CNWSCreature creature) in /home/runner/work/Anvil/Anvil/src/main/NWN/API/Object/NwCreature.cs:line 39
nwn_1    |    at NWN.API.NwModule.get_Players()+MoveNext()
nwn_1    |    at KK2.Game.Features.Autoexp.<ScheduleSAM>b__4_0()
nwn_1    |    at NWN.Services.SchedulerService.NWN.Services.IUpdateable.Update() in /home/runner/work/Anvil/Anvil/src/main/NWN/Services/Scheduler/SchedulerService.cs:line 110
nwn_1    |    at NWN.Services.LoopService.OnLoop() in /home/runner/work/Anvil/Anvil/src/main/NWN/Services/GameLoop/LoopService.cs:line 29
nwn_1    |    at Anvil.Internal.CoreInteropHandler.NWN.Core.ICoreEventHandler.OnMainLoop(UInt64 frame) in /home/runner/work/Anvil/Anvil/src/main/Anvil/Internal/CoreInteropHandler.cs:line 64 System.NullReferenceException: Object reference not set to an instance of an object.
nwn_1    |    at NWN.API.NwCreature..ctor(CNWSCreature creature) in /home/runner/work/Anvil/Anvil/src/main/NWN/API/Object/NwCreature.cs:line 39
nwn_1    |    at NWN.API.NwModule.get_Players()+MoveNext()
nwn_1    |    at KK2.Game.Features.Autoexp.<ScheduleSAM>b__4_0()
nwn_1    |    at NWN.Services.SchedulerService.NWN.Services.IUpdateable.Update() in /home/runner/work/Anvil/Anvil/src/main/NWN/Services/Scheduler/SchedulerService.cs:line 110
nwn_1    |    at NWN.Services.LoopService.OnLoop() in /home/runner/work/Anvil/Anvil/src/main/NWN/Services/GameLoop/LoopService.cs:line 29
nwn_1    |    at Anvil.Internal.CoreInteropHandler.NWN.Core.ICoreEventHandler.OnMainLoop(UInt64 frame) in /home/runner/work/Anvil/Anvil/src/main/Anvil/Internal/CoreInteropHandler.cs:line 64
nwn_1    | I [11:39:54] [NWNX_ServerLogRedirector] [ServerLogRedirector.cpp:80] (Server) *** ValidateGFFResource sent by user.```

**Comment by jakkn** [comment]
I noticed this too, recently. Nice to see it's already tracked :+1:
