### ISSUE TITLE
Skill.AllSkills not working with Effect.SkillIncrease

### ISSUE THREAD

**Issue by Mefi100** [nwn-dotnet/Anvil#659]
code to reproduce issue
`Effect eSkill = Effect.SkillIncrease(Skill.AllSkills, 1);`

stack trace
```
2023-05-16T08:02:39.431341012Z stdout F    at KK2.Game.Feats.BardSong.EventHandler(CallInfo callInfo) in /Build/src/Game/Feats/BardSong.cs:line 93
2023-05-16T08:02:39.431331922Z stdout F    at Anvil.API.Effect.SkillIncrease(NwSkill skill, Int32 amount) in /home/runner/work/Anvil/Anvil/NWN.Anvil/src/main/API/EngineStructures/Effect.Create.cs:line 672
2023-05-16T08:02:39.431326282Z stdout F System.NullReferenceException: Object reference not set to an instance of an object.
```

**Comment by Mefi100** [comment]
Anvil uses `Effect.SkillIncreaseAll` instead, closing.
