### ISSUE TITLE
NwRandom.Roll throws ArgumentOutOfRangeException when passed Int32.MaxValue

### ISSUE THREAD

**Issue by jakkn** [nwn-dotnet/Anvil#722]
https://github.com/nwn-dotnet/Anvil/blob/46e5424db5e976bc5978bdb120c3d4bb64146ea9/NWN.Anvil/src/main/API/NwRandom.cs#L28

I think `randMax` rolls over to ~zero~ `Int32.MinValue` when `sides` is sufficiently large.

I noticed these stack traces in my logs
```txt
bop-test  | E [2023/10/01 09:52:13.312] [Anvil.Services.EventService] An exception was thrown while trying to invoke event "OnPlayerChat". Context Object "7fffffff" - "DM Moon"
bop-test  | System.ArgumentOutOfRangeException: 'minValue' cannot be greater than maxValue. (Parameter 'minValue')
bop-test  |    at System.Random.ThrowMinMaxValueSwapped()
bop-test  |    at System.Random.ThreadSafeRandom.Next(Int32 minValue, Int32 maxValue)
bop-test  |    at Anvil.API.NwRandom.Roll(Random random, Int32 sides, Int32 amount) in /home/runner/work/Anvil/Anvil/NWN.Anvil/src/main/API/NwRandom.cs:line 32
bop-test  |    at Jorteck.Toolbox.Features.DiceRollService.RollDice(NwCreature creature, Int32 numSides, Int32 numDice, RollBroadcastTargets broadcastTargets)
bop-test  |    at Jorteck.Toolbox.Features.RollDiceCommand.ProcessCommand(NwPlayer caller, IReadOnlyList`1 args)
bop-test  |    at Jorteck.Toolbox.Features.Chat.ChatCommandService.TryProcessCommand(NwPlayer sender, String rawCommand)
bop-test  |    at Jorteck.Toolbox.Features.Chat.ChatCommandService.ProcessCommandText(NwPlayer player, String commandText)
bop-test  |    at Jorteck.Toolbox.Features.Chat.ChatCommandService.OnChatMessageSend(OnPlayerChat eventData)
bop-test  |    at Anvil.Services.EventService.EventHandler`1.TryInvoke(T eventData, Action`1 callback) in /home/runner/work/Anvil/Anvil/NWN.Anvil/src/main/Services/Events/EventService.EventHandler.cs:line 103
bop-test  | E [2023/10/01 09:52:13.312] [Anvil.Services.EventService] System.ArgumentOutOfRangeException: 'minValue' cannot be greater than maxValue. (Parameter 'minValue')
bop-test  | System.ArgumentOutOfRangeException: 'minValue' cannot be greater than maxValue. (Parameter 'minValue')
bop-test  |    at System.Random.ThrowMinMaxValueSwapped()
bop-test  |    at System.Random.ThreadSafeRandom.Next(Int32 minValue, Int32 maxValue)
bop-test  |    at Anvil.API.NwRandom.Roll(Random random, Int32 sides, Int32 amount) in /home/runner/work/Anvil/Anvil/NWN.Anvil/src/main/API/NwRandom.cs:line 32
bop-test  |    at Jorteck.Toolbox.Features.DiceRollService.RollDice(NwCreature creature, Int32 numSides, Int32 numDice, RollBroadcastTargets broadcastTargets)
bop-test  |    at Jorteck.Toolbox.Features.RollDiceCommand.ProcessCommand(NwPlayer caller, IReadOnlyList`1 args)
bop-test  |    at Jorteck.Toolbox.Features.Chat.ChatCommandService.TryProcessCommand(NwPlayer sender, String rawCommand)
bop-test  |    at Jorteck.Toolbox.Features.Chat.ChatCommandService.ProcessCommandText(NwPlayer player, String commandText)
bop-test  |    at Jorteck.Toolbox.Features.Chat.ChatCommandService.OnChatMessageSend(OnPlayerChat eventData)
bop-test  |    at Anvil.Services.EventService.EventHandler`1.TryInvoke(T eventData, Action`1 callback) in /home/runner/work/Anvil/Anvil/NWN.Anvil/src/main/Services/Events/EventService.EventHandler.cs:line 103
```
and figured my players are throwing naughty dice. When asked they said they were doing `/roll d1000000000000` but that doesn't throw any errors in testing. `/roll 1d2147483647`, however, does.

It's also curious that it throws twice, any idea why?

**Comment by jakkn** [comment]
Confirmed by debugging.

![image](https://github.com/nwn-dotnet/Anvil/assets/3417835/afe9968f-6838-4f34-baf6-a09d8cf9f724)

Any other values than `1d2147483647` seem to be caught by validation in Toolbox.

**Comment by jhett12321** [comment]
Closing as this is a toolbox bug. Should be fixed with the latest change.

**Comment by jakkn** [comment]
> Closing as this is a toolbox bug. Should be fixed with the latest change.

I somewhat agree that a fix could go to toolbox, but don't you think `NwRandom` needs a check as well? Even though Toolbox is patched, other plugins can still hit this error.

**Comment by jhett12321** [comment]
What would be the expected behaviour? I guess it could throw a custom exception, or `OverflowException`.

**Comment by jakkn** [comment]
Hmm, I initially thought it should be handled with something like `sides = Math.Min(sides, Int32.Max - 1);` and perhaps a logged warning, but I guess throwing a different exception could also work. I mean, the library offers functionality, and one might say that it's the responsibility of the consumer to use the library within its limitations. However, in this case, the library fails to inform the consumer of any limitations. Shouldn't it?
